name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: yarn
      - run: yarn install

      - name: Build
        run: yarn run docs:build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN2 }}
